#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Todo.Web.App.csproj", "."]
RUN dotnet restore "./Todo.Web.App.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Todo.Web.App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Todo.Web.App.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Todo.Web.App.dll"]